// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/echo.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StoredMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,3,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Read          bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	mi := &file_proto_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{3}
}

func (x *StoredMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoredMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoredMessage) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *StoredMessage) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*StoredMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesResponse) GetMessages() []*StoredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MarkMessageAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessageAsReadRequest) Reset() {
	*x = MarkMessageAsReadRequest{}
	mi := &file_proto_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessageAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessageAsReadRequest) ProtoMessage() {}

func (x *MarkMessageAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessageAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkMessageAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{5}
}

func (x *MarkMessageAsReadRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type MarkMessageAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      *StoredMessage         `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessageAsReadResponse) Reset() {
	*x = MarkMessageAsReadResponse{}
	mi := &file_proto_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessageAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessageAsReadResponse) ProtoMessage() {}

func (x *MarkMessageAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessageAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkMessageAsReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{6}
}

func (x *MarkMessageAsReadResponse) GetMessages() *StoredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetMessageByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIDRequest) Reset() {
	*x = GetMessageByIDRequest{}
	mi := &file_proto_echo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIDRequest) ProtoMessage() {}

func (x *GetMessageByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMessageByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageByIDRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type GetMessageByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *StoredMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIDResponse) Reset() {
	*x = GetMessageByIDResponse{}
	mi := &file_proto_echo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIDResponse) ProtoMessage() {}

func (x *GetMessageByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMessageByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageByIDResponse) GetMessage() *StoredMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_echo_proto protoreflect.FileDescriptor

const file_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/echo.proto\x12\x04echo\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x12GetMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"p\n" +
	"\rStoredMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fcreated_unix\x18\x03 \x01(\x03R\vcreatedUnix\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\"F\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.echo.StoredMessageR\bmessages\"9\n" +
	"\x18MarkMessageAsReadRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"L\n" +
	"\x19MarkMessageAsReadResponse\x12/\n" +
	"\bmessages\x18\x01 \x01(\v2\x13.echo.StoredMessageR\bmessages\"6\n" +
	"\x15getMessageByIDRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"G\n" +
	"\x16getMessageByIDResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.echo.StoredMessageR\amessage2\xfa\x02\n" +
	"\vEchoService\x12-\n" +
	"\x04Echo\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\x122\n" +
	"\tUpperCase\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\x12B\n" +
	"\vGetMessages\x12\x18.echo.GetMessagesRequest\x1a\x19.echo.GetMessagesResponse\x12T\n" +
	"\x11MarkMessageAsRead\x12\x1e.echo.MarkMessageAsReadRequest\x1a\x1f.echo.MarkMessageAsReadResponse\x12n\n" +
	"\x0egetMessageByID\x12\x1b.echo.getMessageByIDRequest\x1a\x1c.echo.getMessageByIDResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/messages/{message_id}B\x17Z\x15grpc-echo/proto;protob\x06proto3"

var (
	file_proto_echo_proto_rawDescOnce sync.Once
	file_proto_echo_proto_rawDescData []byte
)

func file_proto_echo_proto_rawDescGZIP() []byte {
	file_proto_echo_proto_rawDescOnce.Do(func() {
		file_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)))
	})
	return file_proto_echo_proto_rawDescData
}

var file_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),               // 0: echo.EchoRequest
	(*EchoResponse)(nil),              // 1: echo.EchoResponse
	(*GetMessagesRequest)(nil),        // 2: echo.GetMessagesRequest
	(*StoredMessage)(nil),             // 3: echo.StoredMessage
	(*GetMessagesResponse)(nil),       // 4: echo.GetMessagesResponse
	(*MarkMessageAsReadRequest)(nil),  // 5: echo.MarkMessageAsReadRequest
	(*MarkMessageAsReadResponse)(nil), // 6: echo.MarkMessageAsReadResponse
	(*GetMessageByIDRequest)(nil),     // 7: echo.getMessageByIDRequest
	(*GetMessageByIDResponse)(nil),    // 8: echo.getMessageByIDResponse
}
var file_proto_echo_proto_depIdxs = []int32{
	3, // 0: echo.GetMessagesResponse.messages:type_name -> echo.StoredMessage
	3, // 1: echo.MarkMessageAsReadResponse.messages:type_name -> echo.StoredMessage
	3, // 2: echo.getMessageByIDResponse.message:type_name -> echo.StoredMessage
	0, // 3: echo.EchoService.Echo:input_type -> echo.EchoRequest
	0, // 4: echo.EchoService.UpperCase:input_type -> echo.EchoRequest
	2, // 5: echo.EchoService.GetMessages:input_type -> echo.GetMessagesRequest
	5, // 6: echo.EchoService.MarkMessageAsRead:input_type -> echo.MarkMessageAsReadRequest
	7, // 7: echo.EchoService.getMessageByID:input_type -> echo.getMessageByIDRequest
	1, // 8: echo.EchoService.Echo:output_type -> echo.EchoResponse
	1, // 9: echo.EchoService.UpperCase:output_type -> echo.EchoResponse
	4, // 10: echo.EchoService.GetMessages:output_type -> echo.GetMessagesResponse
	6, // 11: echo.EchoService.MarkMessageAsRead:output_type -> echo.MarkMessageAsReadResponse
	8, // 12: echo.EchoService.getMessageByID:output_type -> echo.getMessageByIDResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_echo_proto_init() }
func file_proto_echo_proto_init() {
	if File_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_echo_proto_goTypes,
		DependencyIndexes: file_proto_echo_proto_depIdxs,
		MessageInfos:      file_proto_echo_proto_msgTypes,
	}.Build()
	File_proto_echo_proto = out.File
	file_proto_echo_proto_goTypes = nil
	file_proto_echo_proto_depIdxs = nil
}
